scrape_configs:
  - job_name: 'probe_api'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response. --> same name as blackbox exporter configuration
    static_configs:
      - targets:
        #- http://prometheus.io    # Target to probe with http.
        #- https://prometheus.io   # Target to probe with https.
        - https://labcampmonapi.azurewebsites.net/api/labcamp_test_api_probe?code=DoDkKlW4YPCYDNKNYmOb5ZZmXPPccOm9H7SenqUZkzpdZzZbrnzczw==&name=marco
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.56.1:9115  # The blackbox exporter's real hostname:port.
